__version__ = "0.0"

import sys
from meshroom.core import desc
from meshroomMicmac.custom import node

class Campari(node.MicmacNode):
    commandLine = 'mm3d Campari {imagePatternValue} {inputOrientationValue} {OutValue} {allParams}'
    documentation = 'Campari'

    inputs = [
        desc.File(
            name='projectDirectory',
            label='Project Directory',
            description='Project Directory.',
            value="",
            group="micmac",
            uid=[0],
        ),
        desc.File(
            name='imagePattern',
            label='Image Pattern',
            description="Full Directory (Dir+Pattern)",
            uid=[0],
            group='unnamedParams',
            value="",
        ),
        desc.File(
            name='inputOrientation',
            label='Orientation Directory',
            description="Input Orientation",
            uid=[0],
            group='unnamedParams',
            value="",
        ),
        desc.File(
            name='SH',
            label='Homol Directory',
            description="Homol Directory.",
            uid=[0],
            value="",
        ),
     	desc.BoolParam(
            name='enableGpsLa',
            label='Enable GpsLa',
            description="Enable GpsLa.",
            uid=[0],
            value=False,
            group=''
        ),
        desc.GroupAttribute(
            name='GpsLa',
            label='Gps La',
            description="Gps Lever Arm, in combination with EmGPS",
            brackets='[]',
            joinChar=',',
            enabled=lambda node: node.enableGpsLa.value,
            groupDesc=[
            desc.FloatParam(
                name="x",
                label="X",
                description="x.",
                value=0.0,
                range=(-float('inf'), float('inf'), 0.01),
                uid=[0],
            ),
            desc.FloatParam(
                name="y",
                label="Y",
                description="y.",
                value=0.0,
                range=(-float('inf'), float('inf'), 0.01),
                uid=[0],
            ),
            desc.FloatParam(
                name="z",
                label="Z",
                description="z.",
                value=0.0,
                range=(-float('inf'), float('inf'), 0.01),
                uid=[0],
            ),
        ]),
        desc.GroupAttribute(
            name='IncLA',
            label='Inc L A',
            description="Inc on initial value of LA (Def not used)",
            brackets='[]',
            joinChar=',',
            enabled=lambda node: node.enableGpsLa.value,
            groupDesc=[
            desc.FloatParam(
                name="x",
                label="X",
                description="x.",
                value=0.0,
                range=(-float('inf'), float('inf'), 0.01),
                uid=[0],
            ),
            desc.FloatParam(
                name="y",
                label="Y",
                description="y.",
                value=0.0,
                range=(-float('inf'), float('inf'), 0.01),
                uid=[0],
            ),
            desc.FloatParam(
                name="z",
                label="Z",
                description="z.",
                value=0.0,
                range=(-float('inf'), float('inf'), 0.01),
                uid=[0],
            ),
        ]),
        desc.StringParam(
            name='PatGPS',
            label='Pat G P S',
            description="When EmGPS, filter images where GPS is used",
            uid=[0],
            value="",
        ),
        desc.FloatParam(
            name='SigmaTieP',
            label='Sigma Tie P',
            description="Sigma use for TieP weighting (Def=1)",
            uid=[0],
            value=5.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.FloatParam(
            name='FactElimTieP',
            label='Fact Elim Tie P',
            description="Fact elimination of tie point (prop to SigmaTieP, Def=5)",
            uid=[0],
            value=5.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.BoolParam(
            name='CPI1',
            label='C P I1',
            description="Calib Per Im, Firt time",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='CPI2',
            label='C P I2',
            description="Calib Per Im, After first time, reUsing Calib Per Im As input",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='AllFree',
            label='All Free',
            description="Refine all calibration parameters (Def=false)",
            uid=[0],
            value=False,
        ),
        desc.StringParam(
            name='AllFreePat',
            label='All Free Pat',
            description="Pattern of images that will be subject to AllFree (Def=.*)",
            uid=[0],
            value="",
        ),
        desc.StringParam(
            name='GradualRefineCal',
            label='Gradual Refine Cal',
            description="Calibration model to refine gradually",
            uid=[0],
            value="",
        ),
        desc.BoolParam(
            name='DetGCP',
            label='Det G C P',
            description="Detail on GCP (Def=false)",
            uid=[0],
            value=False,
        ),
        desc.FloatParam(
            name='Visc',
            label='Visc',
            description="Viscosity on external orientation in Levenberg-Marquardt like resolution (Def=1.0)",
            uid=[0],
            value=1.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.BoolParam(
            name='AddViscInterne',
            label='Add Visc Interne',
            description="Add Viscosity on calibration parameter (Def=false, exept for GradualRefineCal)",
            uid=[0],
            value=False,
        ),
        desc.FloatParam(
            name='ViscInterne',
            label='Visc Interne',
            description="Viscosity on calibration parameter (Def=0.1), use it with AddViscInterne=true",
            uid=[0],
            value=0.1,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.BoolParam(
            name='ExpTxt',
            label='Exp Txt',
            description="Export in text format (Def=false)",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='PoseFigee',
            label='Pose Figee',
            description="Does the external orientation of the cameras are frozen or free (Def=false, i.e. camera poses are free)",
            uid=[0],
            value=False,
        ),
        desc.StringParam(
            name='FrozenPoses',
            label='Frozen Poses',
            description="List of frozen poses (pattern)",
            uid=[0],
            value="",
        ),
        desc.StringParam(
            name='FrozenCenters',
            label='Frozen Centers',
            description="List of frozen poses (pattern)",
            uid=[0],
            value="",
        ),
        desc.StringParam(
            name='FrozenOrients',
            label='Frozen Orients',
            description="List of frozen poses (pattern)",
            uid=[0],
            value="",
        ),
        desc.BoolParam(
            name='AcceptGB',
            label='Accept G B',
            description="Accepte new Generik Bundle image, Def=true, set false for perfect backward compatibility",
            uid=[0],
            value=False,
        ),
        desc.StringParam(
            name='NameRTA',
            label='Name R T A',
            description="Name for save results of Rolling Test Appuis , Def=SauvRTA.xml",
            uid=[0],
            value="",
        ), 
        desc.IntParam(
            name='NbIterEnd',
            label='Nb Iter End',
            description="Number of iteration at end, Def = 4",
            uid=[0],
            value=4,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.BoolParam(
            name='FocFree',
            label='Foc Free',
            description="Foc Free (Def=true)",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='PPFree',
            label='P P Free',
            description="Principal Point Free (Def=true)",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='AffineFree',
            label='Affine Free',
            description="Affine Parameter (Def=true)",
            uid=[0],
            value=False,
        ),
        desc.IntParam(
            name='DegAdd',
            label='Deg Add',
            description="When specified, degree of additionnal parameter",
            uid=[0],
            value=0,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.IntParam(
            name='DegFree',
            label='Deg Free',
            description="When specified degree of freedom of parameters generiqs",
            uid=[0],
            value=0,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.IntParam(
            name='DRMax',
            label='D R Max',
            description="When specified degree of freedom of radial parameters",
            uid=[0],
            value=0,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.BoolParam(
            name='LibCP',
            label='Lib C P',
            description="Free distorsion center, Def context dependant",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='LibCD',
            label='Lib C D',
            description="Free distorsion center, Def context dependant. Principal Point should be also free if CD is free",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='LibDec',
            label='Lib Dec',
            description="Free decentric parameter, Def context dependant",
            uid=[0],
            value=False,
        ),
        desc.IntParam(
            name='SElimB',
            label='S Elim B',
            description="Print stat on reason for bundle elimination (0,1,2)",
            uid=[0],
            value=0,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.BoolParam(
            name='ExpMatMark',
            label='Exp Mat Mark',
            description="Export Cov Matrix to Matrix Market Format+Eigen/cmp",
            uid=[0],
            value=False,
        ),
        desc.StringParam(
            name='SauvAutom',
            label='Sauv Autom',
            description="Save intermediary results to, Set NONE if dont want any",
            uid=[0],
            value="",
        ),
        desc.FloatParam(
            name='RatioMaxDistCS',
            label='Ratio Max Dist C S',
            description="Ratio max of distance P-Center",
            uid=[0],
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.IntParam(
            name='NbLiais',
            label='Nb Liais',
            description="Param for relative weighting for tie points",
            uid=[0],
            value=100,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.FloatParam(
            name='PdsGBRot',
            label='Pds G B Rot',
            description="Weighting of the global rotation constraint (Generic bundle Def=0.002)",
            uid=[0],
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.FloatParam(
            name='PdsGBId',
            label='Pds G B Id',
            description="Weighting of the global deformation constraint (Generic bundle Def=0.0)",
            uid=[0],
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.FloatParam(
            name='PdsGBIter',
            label='Pds G B Iter',
            description="Weighting of the change of the global rotation constraint between iterations (Generic bundle Def=1e-6)",
            uid=[0],
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.BoolParam(
            name='ExportSensib',
            label='Export Sensib',
            description="Export sensiblity (accuracy) estimator : correlation , variance, inverse matrix variance ...",
            uid=[0],
            value=False,
        ),
        desc.BoolParam(
            name='UseGaussJ',
            label='Use Gauss J',
            description="Use GaussJ instead of Cholesky (Def depend of others)",
            uid=[0],
            value=False,
        ),
        desc.IntParam(
            name='NormEq',
            label='Norm Eq',
            description="Flag for Norm Eq, 1->Sc, 2-Tr, Def=3 (All), tuning purpose",
            uid=[0],
            value=3,
            range=(-sys.maxsize, sys.maxsize, 1),
        ),
        desc.StringParam(
            name='StrDebugVTP',
            label='Str Debug V T P',
            description="String of debug for tie points",
            uid=[0],
            value="",
        ),
        desc.IntParam(
            name='NAWNF',
            label='N A W N F',
            description="Num Attribute for Weigthing in New Format",
            uid=[0],
            value=0,
            range=(-sys.maxsize, sys.maxsize, 1),
        ), 
        desc.FloatParam(
            name='WOP',
            label='W O P',
            description="Weight of plane observation on centers",
            uid=[0],
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
        desc.FloatParam(
            name='ExtIntZ',
            label='Ext Int Z',
            description="Extension of Z Interval for elimination",
            uid=[0],
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
        ),
    ]

    outputs = [
        desc.File(
            name='Out',
            label='Orientation Directory',
            description="Output Orientation",
            uid=[0],
            group='unnamedParams',
            value="Campari",
        ), 
    ]
